---
- hosts: jenkins
  become: true
  
  vars:
    jenkins_hostname: jenkins.home
    java_packages:
      - java-11-openjdk
    jenkins_admin_username: admin
    jenkins_admin_password: admin 

  roles:
    - role: geerlingguy.java
    - role: geerlingguy.jenkins
  tasks:
  - name: add ports
    firewalld:
      port: 8080/tcp
      permanent: yes
      state: enabled
  - name: reload service firewalld
    systemd:
      name: firewalld
      state: reloaded 
