---
- hosts: jenkins
  become: true
  
  vars:
    jenkins_hostname: jenkins.home
    java_packages:
      - java-11-openjdk
    jenkins_admin_username: admin
    jenkins_admin_password: admin 
    jenkins_plugins:
      - javax-activation-api
      - javax-mail-api
      - sshd
      - cloudbees-folder
      - antisamy-markup-formatter
      - structs
      - workflow-step-api
      - token-macro
      - build-timeout
      - credentials
      - trilead-api
      - ssh-credentials
      - plain-credentials
      - credentials-binding
      - scm-api
      - workflow-api
      - timestamper
      - caffeine-api
      - script-security
      - plugin-util-api
      - font-awesome-api
      - popper-api
      - jquery3-api
      - bootstrap4-api
      - snakeyaml-api
      - jackson2-api
      - popper2-api
      - bootstrap5-api
      - echarts-api
      - display-url-api
      - workflow-support
      - checks-api
      - junit
      - matrix-project
      - resource-disposer
      - ws-cleanup
      - ant
      - jaxb
      - durable-task
      - workflow-durable-task-step
      - jdk-tool
      - command-launcher
      - bouncycastle-api
      - ace-editor
      - workflow-scm-step
      - workflow-cps
      - workflow-job
      - apache-httpcomponents-client-4-api
      - mailer
      - workflow-basic-steps
      - gradle
      - pipeline-milestone-step
      - pipeline-input-step
      - pipeline-stage-step
      - pipeline-graph-analysis
      - pipeline-rest-api
      - handlebars
      - momentjs
      - pipeline-stage-view
      - pipeline-build-step
      - pipeline-model-api
      - pipeline-model-extensions
      - jsch
      - git-client
      - git-server
      - workflow-cps-global-lib
      - branch-api
      - workflow-multibranch
      - pipeline-stage-tags-metadata
      - pipeline-model-definition
      - lockable-resources
      - workflow-aggregator
      - jjwt-api
      - okhttp-api
      - github-api
      - git
      - github
      - github-branch-source
      - pipeline-github-lib
      - ssh-slaves
      - matrix-auth
      - jnr-posix-api
      - pam-auth
      - ldap
      - email-ext
      - docker-workflow

  roles:
    - role: geerlingguy.java
    - role: geerlingguy.jenkins
  tasks:
  - name: add ports ui
    firewalld:
      port: 8080/tcp
      permanent: yes
      state: enabled
  - name: add ports jnlp
    firewalld:
      port: 5000/tcp
      permanent: yes
      state: enabled      
  - name: reload service firewalld
    systemd:
      name: firewalld
      state: reloaded 
  - name: configure jenkins
    jenkins_script:
      url: "http://localhost:8080"
      script: >-
        {{ lookup('template', 'scripts/configjenkins.j2') }}
      user: admin
      password: admin     

