---
- hosts: jenkins.home
  become: true
  
  vars_files:
    - defaults.yml  
  vars:
    jenkins_version: 2.332
    java_packages:
      - java-11-openjdk
    jenkins_http_port: 8080
    jenkins_java_options: "-Djenkins.install.runSetupWizard=false -Dcasc.jenkins.config=/var/lib/jenkins/casc"
    jenkins_plugins:
      - name: "javax-activation-api"
        version: "1.2.0-2"
      - name: "javax-mail-api"
        version: "1.6.2-5"
      - name: "sshd"
        version: "3.1.0"
      - name: "cloudbees-folder"
        version: "6.708.ve61636eb_65a_5"
      - name: "antisamy-markup-formatter"
        version: "2.7"
      - name: "structs"
        version: "308.v852b473a2b8c"
      - name: "token-macro"
        version: "280.v97a_82642793c"
      - name: "build-timeout"
        version: "1.20"
      - name: "credentials"
        version: "1074.v60e6c29b_b_44b_"
      - name: "trilead-api"
        version: "1.0.13"
      - name: "ssh-credentials"
        version: "1.19"
      - name: "workflow-step-api"
        version: "622.vb_8e7c15b_c95a_"
      - name: "plain-credentials"
        version: "1.8"
      - name: "credentials-binding"
        version: "1.27.1"
      - name: "scm-api"
        version: "595.vd5a_df5eb_0e39"
      - name: "workflow-api"
        version: "1138.v619fd5201b_2f"
      - name: "timestamper"
        version: "1.17"
      - name: "caffeine-api"
        version: "2.9.2-29.v717aac953ff3"
      - name: "script-security"
        version: "1140.vf967fb_efa_55a_"
      - name: "plugin-util-api"
        version: "2.14.0"
      - name: "font-awesome-api"
        version: "6.0.0-1"
      - name: "popper-api"
        version: "1.16.1-2"
      - name: "jquery3-api"
        version: "3.6.0-2"
      - name: "bootstrap4-api"
        version: "4.6.0-3"
      - name: "snakeyaml-api"
        version: "1.29.1"
      - name: "jackson2-api"
        version: "2.13.1-246.va8a9f3eaf46a"
      - name: "popper2-api"
        version: "2.11.2-1"
      - name: "bootstrap5-api"
        version: "5.1.3-6"
      - name: "echarts-api"
        version: "5.3.0-2"
      - name: "display-url-api"
        version: "2.3.5"
      - name: "workflow-support"
        version: "815.vd60466279fc8"
      - name: "checks-api"
        version: "1.7.2"
      - name: "junit"
        version: "1.56"
      - name: "matrix-project"
        version: "758.v7a_ea_491852f3"
      - name: "resource-disposer"
        version: "0.17"
      - name: "ws-cleanup"
        version: "0.40"
      - name: "pipeline-milestone-step"
        version: "100.v60a_03cd446e1"
      - name: "pipeline-build-step"
        version: "2.16"
      - name: "pipeline-model-api"
        version: "2.2064.v5eef7d0982b_e"
      - name: "jaxb"
        version: "2.3.0.1"
      - name: "jdk-tool"
        version: "1.5"
      - name: "command-launcher"
        version: "1.6"
      - name: "bouncycastle-api"
        version: "2.25"
      - name: "ace-editor"
        version: "1.1"
      - name: "workflow-scm-step"
        version: "2.13"
      - name: "workflow-cps"
        version: "2660.vb_c0412dc4e6d"
      - name: "pipeline-stage-step"
        version: "291.vf0a8a7aeeb50"
      - name: "workflow-job"
        version: "1174.vdcb_d054cf74a_"
      - name: "pipeline-model-extensions"
        version: "2.2064.v5eef7d0982b_e"
      - name: "apache-httpcomponents-client-4-api"
        version: "4.5.13-1.0"
      - name: "jsch"
        version: "0.1.55.2"
      - name: "git-client"
        version: "3.11.0"
      - name: "git-server"
        version: "1.10"
      - name: "workflow-cps-global-lib"
        version: "564.ve62a_4eb_b_e039"
      - name: "mailer"
        version: "408.vd726a_1130320"
      - name: "branch-api"
        version: "2.7.0"
      - name: "workflow-multibranch"
        version: "711.vdfef37cda_816"
      - name: "durable-task"
        version: "493.v195aefbb0ff2"
      - name: "workflow-durable-task-step"
        version: "1121.va_65b_d2701486"
      - name: "pipeline-stage-tags-metadata"
        version: "2.2064.v5eef7d0982b_e"
      - name: "pipeline-input-step"
        version: "446.vf27b_0b_83500e"
      - name: "workflow-basic-steps"
        version: "941.vdfe1b_a_132c64"
      - name: "pipeline-model-definition"
        version: "2.2064.v5eef7d0982b_e"
      - name: "lockable-resources"
        version: "2.14"
      - name: "workflow-aggregator"
        version: "2.7"
      - name: "jjwt-api"
        version: "0.11.2-9.c8b45b8bb173"
      - name: "okhttp-api"
        version: "4.9.3-105.vb96869f8ac3a"
      - name: "github-api"
        version: "1.301-378.v9807bd746da5"
      - name: "git"
        version: "4.10.3"
      - name: "github"
        version: "1.34.3"
      - name: "github-branch-source"
        version: "1583.v18d333ef7379"
      - name: "pipeline-github-lib"
        version: "36.v4c01db_ca_ed16"
      - name: "pipeline-graph-analysis"
        version: "188.v3a01e7973f2c"
      - name: "pipeline-rest-api"
        version: "2.23"
      - name: "handlebars"
        version: "3.0.8"
      - name: "momentjs"
        version: "1.1.1"
      - name: "pipeline-stage-view"
        version: "2.23"
      - name: "matrix-auth"
        version: "3.1"
      - name: "jnr-posix-api"
        version: "3.1.7-2"
      - name: "pam-auth"
        version: "1.7"
      - name: "ldap"
        version: "2.8"
      - name: "email-ext"
        version: "2.87"
      - name: "configuration-as-code"
        version: "1414.v878271fc496f"
      - name: "deployit-plugin"
        version: "22.0.0"
      - name: "docker-commons"
        version: "1.19"
      - name: "docker-workflow"
        version: "1.28"
      - name: "authentication-tokens"
        version: "1.3"
        
  roles:
    - role: geerlingguy.java
    - role: geerlingguy.jenkins
    - role: geerlingguy.git
  tasks:
    - name: create 
      ansible.builtin.file:
        path: /var/lib/jenkins/casc
        state: directory
        mode: u+rwx,g-rwx,o-rx
        owner: jenkins
        group: jenkins  
    - name: copy service file
      copy:
        content: "{{ lookup('template', 'scripts/jenkins.yml') }}"
        dest: /var/lib/jenkins/casc/jenkins.yml
        owner: jenkins
        group: jenkins
        mode: u+rwx,g-rwx,o-rx
    - name: add ports ui
      firewalld:
        port: "{{jenkins_http_port}}/tcp"
        permanent: yes
        state: enabled
    - name: add ports jnlp
      firewalld:
        port: 5000/tcp
        permanent: yes
        state: enabled      
    - name: reload service firewalld
      systemd:
        name: firewalld
        state: reloaded 
    - name: configure jenkins
      jenkins_script:
        url: "http://localhost:{{jenkins_http_port}}"
        script: >-
          {{ lookup('template', 'scripts/configjenkins.j2') }}
        user: "{{jenkins_admin_username}}"
        password: "{{jenkins_admin_password}}"

